const words = {
    characteristic: [
        "sexy",
        "cold-hearted",
        "mysterious",
        "sympathetic",
        "unassuming",
        "hot-headed",
        "sadistic",
        "beautiful",
        "rude",
        "fanatical",
        "cannibalistic",
        "masochistic",
        "wealthy",
        "seductive",
        "ugly",
        "angelic",
        "aggresive",
        "pacifistic",
        "buff",
        "fiery",
        "devilish",
        "cruel",
        "sweet",
        "quiet",
        "adventurous",
        "ambitious",
        "affectionate",
        "amiable",
        "considerate",
        "courageous",
        "generous",
        "impartial",
        "judgemental",
        "passionate",
        "persistant",
        "determined",
        "rational",
        "irrational",
        "resourceful",
        "reliable",
        "sincere",
        "witty",
        "clever",
        "boastful",
        "bold",
        "athletic",
        "acrobatic",
        "arrogant",
        "annoying",
        "articulate",
        "awkward",
        "clumsy",
        "cheerful",
        "conceited",
        "haughty",
        "careless",
        "careful",
        "calm",
        "confident",
        "dainty",
        "daring",
        "devout",
        "disgruntled",
        "efficient",
        "energetic",
        "eager",
        "gorgeous",
        "fancy",
        "fashionable",
        "funny",
        "grouchy",
        "gracious",
        "handsome",
        "impulsive",
        "jealous",
        "greedy",
        "envious",
        "wrathful",
        "lazy",
        "likeable",
        "manipulative",
        "mature",
        "melancholy",
        "mischievous",
        "obnoxious",
        "organized",
        "patient",
        "plain",
        "popular",
        "proud",
        "radical",
        "reserved",
        "rich",
        "sarcastic",
        "cynical",
        "short",
        "petite",
        "studious",
        "successful",
        "sensitive",
        "selfish",
        "selfless",
        "vain",
        "wild",
        "wise",
        "anonymous",
        "shady",
        "guarded",
        "cryptic",
        "disgraced"
    ],

    peopleF: [
        "sorcerer",
        "headless horseman",
        "paladin",
        "warlock",
        "wizard",
        "druid",
        "cleric",
        "barbarian",
        "fighter",
        "rogue",
        "ranger",
        "bard",
        "medusa",
        "king",
        "knight",
        "crime lord",
        "cult leader",
        "priestess",
        "advisor",
        "acolyte",
        "archmage",
        "queen",
        "assassin",
        "kobold",
        "cloud giant",
        "hill giant",
        "stone giant",
        "frost giant",
        "fire giant",
        "demon",
        "devil",
        "doppleganger",
        "fire elemental",
        "water elemental",
        "air elemental",
        "earth elemental",
        "goblin",
        "rakshasa",
        "shapeshifter",
        "vampire",
        "werewolf",
        "lich",
        "green dragon",
        "red dragon",
        "gold dragon",
        "blue dragon",
        "white dragon",
        "copper dragon",
        "black dragon",
        "brass dragon",
        "bronze dragon",
        "silver dragon",
        "mage",
        "thief",
        "warrior",
        "monarch",
        "priest",
        "lamia",
        "hunter",
        "bartender",
        "con artist",
        "artist",
        "vigilante",
        "necromancer",
        "emperor",
        "emperess",
        "lord",
        "lady",
        "duke",
        "dutchess",
        "servant",
        "aberration",
        "golem",
        "spirit",
        "spy",
        "fey creature",
        "mind flayer",
        "blacksmith",
        "soldier",
        "wizard",
        "shopkeep",
        "undead",
        "pirate",
        "graverobber",
        "executioner",
        "hero",
        "diplomat",
        "farmer",
        "sailor",
        "captain",
        "writer",
        "celestial",
        "beholder",
        "hag",
        "witch",
        "yaun-ti",
        "merfolk",
        "dracolich",
        "demilich",
        "revenant",
        "death knight",
        "ghost",
        "dryad",
        "genie",
        "djinn",
        "efreet",
        "marid",
        "dao",
        "naga",
        "guard"
    ],

    peopleS: [
        "robot",
        "cyborg",
        "AI",
        "mutant",
        "CEO",
        "company board member",
        "millionaire",
        "clone",
        "scoundrel",
        "pilot",
        "general",
        "alien",
        "president",
        "dictator",
        "thief",
        "assassin",
        "doctor",
        "hacker",
        "con artist",
        "heiress",
        "senator",
        "spy",
        "diplomat",
        "captain",
        "smuggler",
        "bounty hunter",
        "programmer",
        "ambassador",
        "bartender",
        "businessman",
        "mechanic",
        "mercenary",
        "cop",
        "gunslinger",
        "scientist",
        "android",
        "surgeon",
        "heir",
        "brain in a jar",
        "executive",
        "researcher",
        "fixer",
        "freelancer",
        "government official",
        "secret police officer",
        "military officer",
        "first mate",
        "bodyguard",
        "aristocrat",
        "crime lord",
        "mafia don",
        "merchant",
        "explorer",
        "cyberterrorist",
        "corporate agent",
        "corporate spy",
        "corporate assassin",
        "human-alien hybrid",
        "human-animal hybrid",
        "digitized brain",
        "vigilante",
        "alien cyborg",
        "alien AI",
        "alien android",
        "alien robot",
        "alien spy",
        "alien assassin",
        "alien dictator",
        "alien overlord",
        "drug runner",
        "hacktavist",
        "contract killer",
        "freelance spy",
        "double agent",
        "rebel",
        "sharpshooter",
        "psionic",
        "psychic",
        "superhuman",
        "mutated alien",
        "alien hacker",
        "AI hacker",
        "space commando",
        "space marine",
        "alien commando",
        "billionaire",
        "queen",
        "monarch",
        "prime minister",
        "king"
    ],

    backstoriesF: [
        "was betrayed by a close friend",
        "was abandoned by their companions",
        "lost their lover in an attack",
        "was an adventurer",
        "was a war hero",
        "was a notorious criminal",
        "was nearly killed by a hero",
        "betrayed a close friend",
        "abandoned their god",
        "corrupted another person",
        "kidnapped people",
        "cursed someone",
        "killed a hero",
        "abandoned a hero",
        "abandoned a king",
        "transformed someone into a monster",
        "betrayed their mentor",
        "escaped a monster attack",
        "was abandoned by their god",
        "was corrupted by an evil god",
        "was kidnapped by a cult",
        "was kidnapped by a monster",
        "was cursed by a powerful being",
        "was killed by a hero",
        "was abandoned by a hero",
        "was abandoned by a king",
        "was villified because of who they were",
        "was villified over a misunderstanding",
        "was villified because of their family",
        "was transformed into a monster by a powerful being",
        "was betrayed by their mentor",
        "was wrongfully accused of murder",
        "murdered someone",
        "lost their family in an attack",
        "lost their child in an attack",
        "lost their parents in an attack",
        "was a wanted criminal",
        "was an infamous thief",
        "was a famous adventurer",
        "was a heroic adventurer",
        "was a renowned artisan",
        "was an unknown artisan",
        "was a renowned scholar",
        "was a scholar",
        "mentored a famous adventurer",
        "mentored an infamous villain",
        "stole an important artifact",
        "found a cursed artifact",
        "stole a cursed artifact",
        "was a famous chef",
        "escaped prison",
        "smuggled contraband",
        "was enthralled by a monster",
        "was enthralled via magic",
        "lost a limb in an accident",
        "sold their soul to a powerful creature",
        "dedicated their life to a god",
        "was sacrificed to a god",
        "was sacrificed to an evil lord"
    ],

    backstoriesS: [
        "was accused of unethical testing",
        "was fired for unethical practices",
        "was fired for illegal practices",
        "was betrayed by a close friend",
        "was abandoned by their companions",
        "lost their lover in an attack",
        "was a war hero",
        "was a notorious criminal",
        "was nearly killed by a hero",
        "betrayed a close friend",
        "corrupted another person",
        "kidnapped people",
        "killed a hero",
        "abandoned a hero",
        "betrayed their mentor",
        "was killed by a hero",
        "was abandoned by a hero",
        "was villified because of who they were",
        "was villified over a misunderstanding",
        "was villified because of their family",
        "was villified because of their nature",
        "was betrayed by their mentor",
        "was wrongfully accused of murder",
        "murdered someone",
        "lost their family in an attack",
        "lost their child in an attack",
        "lost their parents in an attack",
        "was a wanted criminal",
        "was an infamous thief",
        "mentored an infamous villain",
        "stole an important artifact",
        "was a famous chef",
        "escaped prison",
        "smuggled contraband",
        "lost a limb in an accident",
        "turned into a cyborg",
        "discovered they were not who they thought they were",
        "inherited a lot of money",
        "inherited a company",
        "was promoted to a high position",
        "was a decorated soldier",
        "lost all their memories",
        "was complicit in war crimes",
        "was complicit in genocide",
        "embezzled funds",
        "was wrongfullly accused of embezzling funds",
        "lost their ship in an attack",
        "lost their crew in an attack",
        "was brainwashed by a scientist",
        "was brainwashed into a soldier",
        "was enlisted into the army",
        "was conscripted into the army",
        "deserted the army",
        "stole important files",
        "committed corporate espionage",
        "committed fraud",
        "stole corporate secrets",
        "was experimented on by scientists",
        "was experimented on by researchers",
        "was experimented on by the government",
        "was blackmailed into commiting crimes",
        "was blackmailed into service to someone more powerful",
        "took down a corrupt government",
        "took down a corporation",
        "discovered their memories were erased",
        "discovered their memories are false",
        "discovered their mentor killed their parents",
        "discovered their mentor kidnapped them as a child",
        "was diagnosed with a terminal disease",
        "learned they only had a year to live",
        "was a wanted fugitive",
        "discovered an evil plot",
        "invented a new technology",
        "sold their corporation",
        "created a corporation",
        "lost their corporation to a hostile takeover",
        "lost their riches",
        "lost their inheritance",
        "was a social pariah",
        "was disowned by their family",
        "was unfairly fired",
        "was unfairly stripped of their position",
        "was unfairly stripped of their title",
        "faked their own death",
        "was almost killed by an assassin",
        "was almost killed by their close friend",
        "was almost killed by their mentor",
        "was almost killed by a rival",
        "was almost killed by their sibling",
        "was almost killed by their lover"
    ],

    currentStoriesF: [
        "a serial killer",
        "trying to take over the world",
        "resurrecting an evil god",
        "trying to become a god",
        "running a cult",
        "running a crime organization",
        "corrupting the innocent",
        "spying on their enemies",
        "trying to kill the monarch",
        "sacrificing people",
        "collecting powerful artifacts",
        "building an army",
        "conquering a nation",
        "razing villages",
        "committing mass murder",
        "resurrecting a powerful creature",
        "waking up a powerful creature",
        "controlling a powerful creature",
        "capturing powerful creatures",
        "corrupting powerful creatures",
        "corrupting heroes",
        "chasing the heroes",
        "killing the innocent",
        "breaking people out of prison",
        "instigating war",
        "assassinating powerful people",
        "controlling the monarch",
        "brainwashing people",
        "transforming people into monsters",
        "causing a peasant uprising",
        "committing atrocities",
        "executing their rivals",
        "executing their critics",
        "quashing a revolution",
        "freeing prisoners",
        "sacrificing virgins",
        "flooding the world",
        "draining the oceans",
        "reversing time",
        "raising the dead",
        "draining lifeforces",
        "razing forests",
        "causing earthquakes",
        "causing massive floods",
        "raiding towns",
        "robbing travelers",
        "poisoning civilians",
        "robbing graves",
        "invading other planes",
        "invading the material plane",
        "invading other nations",
        "burning down forests",
        "burning down towns",
        "wiping out towns",
        "creating dangerous artifacts",
        "destroying magical artifacts",
        "spreading a plague",
        "wiping out entire species",
        "torturing civilians",
        "torturing innocents",
        "experimenting on civilians",
        "experimenting on creatures",
        "performing inhumane experiments",
        "burning down temples",
        "razing temples",
        "building an army",
        "building an army of the undead",
        "building an army of monsters",
        "razing crops",
        "poisoning the water",
        "starting a revolution"
    ],

    currentStoriesS: [
        "a serial killer",
        "running a crime organization",
        "corrupting the innocent",
        "spying on their enemies",
        "building an army",
        "conquering a nation",
        "committing mass murder",
        "corrupting heroes",
        "chasing the heroes",
        "killing the innocent",
        "breaking people out of prison",
        "instigating war",
        "assassinating powerful people",
        "brainwashing people",
        "causing a worker uprising",
        "causing a robot uprising",
        "causing an android uprising",
        "causing an alien uprising",
        "causing a civil war",
        "starting a corporate war",
        "starting an interplanetary war",
        "committing atrocities",
        "salvaging derlict ships",
        "salvaging from an abandoned space station",
        "exploring untouched planets",
        "exploring dangerous planets",
        "executing their rivals",
        "executing their critics",
        "quashing a revolution",
        "freeing prisoners",
        "robbing civilians",
        "poisoning civilians",
        "invading other nations",
        "spreading a virus",
        "wiping out entire species",
        "torturing civilians",
        "torturing innocents",
        "torturing prisoners",
        "experimenting on prisoners",
        "experimenting on civilians",
        "performing inhumane experiments",
        "performing biological experiments",
        "performing technological experiments",
        "building an army",
        "starting a revolution",
        "targetting rival companies",
        "building a robotic army",
        "creating a military state",
        "destroying ships",
        "stealing ships",
        "taking over ships",
        "wiping out planets",
        "destroying planets",
        "wiping out aliens",
        "wiping out humans",
        "killing humans",
        "killing aliens",
        "experimenting on aliens",
        "taking over space stations",
        "destroying space stations",
        "hacking important documents",
        "creating computer viruses",
        "creating deadly viruses",
        "destroying technology",
        "creating new technology",
        "developing new technology",
        "conquering other planets",
        "conquering space stations",
        "invading other planets",
        "spying on rival companies",
        "taking down companies",
        "experimenting on humans",
        "experimenting on cyborgs",
        "cloning people",
        "taking over governments",
        "robbing corporations",
        "oppressing civilians",
        "creating dangerous technology",
        "destroying planets",
        "razing planets",
        "monopolizing the water supply",
        "monopolizing the food supply",
        "monopolizing technology"
    ],

    goalsF: [
        "get rich",
        "get revenge",
        "save the world",
        "save their lover",
        "save their child",
        "save themself",
        "stop someone worse than them",
        "become more powerful",
        "defeat a rival",
        "enact their final plan",
        "resurrect their lover",
        "resurrect their family",
        "kill their enemies",
        "entrap the heroes",
        "entrap their enemies",
        "prove their point",
        "win a bet",
        "destroy the world",
        "commit genocide",
        "win back their lover",
        "find a powerful artifact",
        "punish their enemies",
        "sow discord",
        "create order",
        "find someone worthy of challenging them",
        "destroy all those capable of challenging them",
        "control all magic",
        "control all technology",
        "control all knowledge",
        "ensure the survival of their people",
        "fulfill a deal",
        "gain access to paradise",
        "regain their memories",
        "cure themself",
        "pay back a debt",
        "gain their honor back",
        "make the world a better place",
        "break a curse",
        "break a spell",
        "thwart another villainous plot",
        "gain more knowledge",
        "be loved",
        "be feared",
        "be respected",
        "find love",
        "prevent a prophecy from being fulfilled",
        "fulfill a prophecy",
        "create a powerful army",
        "destroy all magic",
        "destroy all technology",
        "destroy all knowledge",
        "suppress all knowledge",
        "gain immortality",
        "understand death",
        "end death",
        "resurrect their lover",
        "resurrect their child",
        "resurrect their mentor",
        "kill their mortal enemy",
        "get revenge on the heroes",
        "impress a god",
        "kill a god",
        "defeat a god"
    ],

    goalsS: [
        "get rich",
        "get revenge",
        "save their lover",
        "save their child",
        "save themself",
        "stop someone worse than them",
        "become more powerful",
        "defeat a rival",
        "enact their final plan",
        "kill their enemies",
        "entrap the heroes",
        "entrap their enemies",
        "prove their point",
        "win a bet",
        "commit genocide",
        "win back their lover",
        "punish their enemies",
        "sow discord",
        "create order",
        "find someone worthy of challenging them",
        "destroy all those capable of challenging them",
        "control all technology",
        "control all knowledge",
        "ensure the survival of their people",
        "fulfill a deal",
        "regain their memories",
        "cure themself",
        "pay back a debt",
        "gain their honor back",
        "make the universe a better place",
        "thwart another villainous plot",
        "gain more knowledge",
        "be loved",
        "be feared",
        "be respected",
        "find love",
        "create a powerful army",
        "destroy all technology",
        "destroy all knowledge",
        "suppress all knowledge",
        "understand death",
        "end death",
        "kill their mortal enemy",
        "get revenge on the heroes",
        "eliminate aliens",
        "eliminate humans",
        "create a monopoly",
        "increase sales",
        "increase revenue",
        "stop wars",
        "create galactic peace"
    ],
    
    adj: [
        "scary",
        "mean",
        "monstrous",
        "sexy",
        "dumb",
        "sympathetic",
        "hot",
        "lame",
        "weird",
        "dangerous",
        "evil",
        "spooky",
        "complex",
        "creepy",
        "terrible",
        "realistic",
        "strange",
        "absurd",
        "oppressive"
    ]
}